### ISSUE TITLE
Unable to get the files in data and models

### ISSUE THREAD

**Issue by yashagrawal115** [tkim-snu/GLACNet#4]
I am unable to get the files in the data folder and files in models folder.

**Comment by tkim-snu** [comment]
You should follow the instructions in the README file.

You can download the data from the following link.
http://visionandlanguage.net/VIST/dataset.html

You can also download the pretrained model from the following link.
https://drive.google.com/drive/folders/10vBPeETCKZfdOr2zenB_WlmKDcRBHmYR?usp=sharing

**Comment by xinli2008** [comment]
hello,thank you for your excellent job on VIST,and i very want to reproduced your project.
i follow the instruction in the README file,because the VIST dataset is big ,so i want to download the pretrained model above.
Can i ask you two question?
①.Which folder should I put the downloaded files in?
②.Can i start training directly next to run python3 train.py?
I am so sorry to bother you and i hope you can give me some useful advice?
@tkim-snu

**Comment by shaoniana1997** [comment]
the file directory is model,misc,data,Which folder should I put the downloaded files(decoder-0.pkl,encoder-0.pkl,vocab.pkl) in?
I am so sorry to bother you !

**Comment by xinli2008** [comment]
I have solved the problem,sorry to bother you.
